name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug commands
        run: |
          echo "Current directory: $(pwd)"
          echo "Next version: $(npm list next | grep next)"
          echo "Next config: $(cat next.config.js)"

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Check for output directory
        run: |
          ls -la
          if [ -d "./out" ]; then
            echo "Output directory exists"
            ls -la ./out
          else
            echo "Output directory does not exist"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 